version: "3.9"
services:   
  selenium:
    image: selenium/standalone-chrome:4.2.2-20220622
    shm_size: 2gb
    ports:
    - 4444:4444
    - 6900:5900
    healthcheck:
      test: /opt/bin/check-grid.sh --host 0.0.0.0 --port 4444
      interval: 10s
      timeout: 30s
      retries: 7
      start_period: 1s  

  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20220622
    volumes:
      - ./tmp/videos:/videos
    depends_on:
      selenium:
        condition: service_healthy
    environment:
      - DISPLAY_CONTAINER_NAME=selenium
      - FILE_NAME=chrome_video.mp4

  redis:
    image: redis:5
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/ChannelsTest
    command: python manage.py test
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      selenium:
        condition: service_healthy
      redis:
        condition: service_started
