version: "3.9"
services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/ChannelsTest
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - selenium
      - redis
